#include <conio.h>
#include <iostream.h>

void main ()
{
cout <<"EEEEEEEEE          FFFFFFFFFF          III\n";
cout <<"EEEEEEEEE          FFFFFFFFFF          III\n";
cout <<"EEEE               FFFF                III\n";
cout <<"EEEE               FFFF                III\n";
cout <<"EEEEEEEEE          FFFFFFFFFF          III\n";
cout <<"EEEEEEEEE          FFFFFFFFFF          III\n";
cout <<"EEEE               FFFF                III\n";
cout <<"EEEE               FFFF                III\n";
cout <<"EEEEEEEEE          FFFF                III\n";
cout <<"EEEEEEEEE          FFFF                III\n";

getch();
}

